<Project>
    <PropertyGroup>
        <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
        <CentralPackageFloatingVersionsEnabled>true</CentralPackageFloatingVersionsEnabled>
        <CentralPackageTransitivePinningEnabled>true</CentralPackageTransitivePinningEnabled>
    </PropertyGroup>

    <ItemGroup>
        <PackageVersion Include="OpenMcdf" Version="2.4.1"/>
    </ItemGroup>

    <ItemGroup>
        <PackageVersion Include="Nuke.Common" Version="10.1.0"/>
        <PackageVersion Include="Nuke.Components" Version="10.1.0"/>
    </ItemGroup>

    <ItemGroup>
        <GlobalPackageReference Include="Polyfill" Version="10.8.1" PrivateAssets="all"/>
    </ItemGroup>
</Project>