<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <PackageType>MSBuildSdk</PackageType>
        <TargetFramework>netstandard2.0</TargetFramework>
    </PropertyGroup>

    <PropertyGroup>
        <Title>Autodesk.Revit.Sdk.Refs</Title>
        <PackageId>Autodesk.Revit.Sdk.Refs</PackageId>
    </PropertyGroup>

    <ItemGroup>
        <Content Include="Sdk/**/*.props" PackagePath="Sdk/"/>
        <Content Include="Sdk/**/*.targets" PackagePath="Sdk/"/>

        <None Include="../../.github/workflows/*.yml" LinkBase="ci"/>

        <Content Include="../../assets/Revit.png" Pack="true" PackagePath="Revit.png"/>
        <Content Include="../../assets/README.md" Pack="true" PackagePath="README.md"/>
        <Content Include="../../assets/LICENSE.md" Pack="true" PackagePath="LICENSE.md"/>
    </ItemGroup>

    <Target Name="Version" AfterTargets="Pack">
        <WriteLinesToFile File="$(PackageOutputPath)\package-version.txt" Lines="$(PackageVersion)"/>
    </Target>
</Project>
