<Project Sdk="Autodesk.Revit.Sdk.Refs/2.0.0">

    <PropertyGroup>
        <UseWpf>true</UseWpf>
        <ShowBuildInfo>true</ShowBuildInfo>
        <IncludeEmbeddedLibrary>true</IncludeEmbeddedLibrary>
        <RootNamespace>RevitPlugin.SingleAssembly</RootNamespace>
        <Configurations>Debug;Release;D2016;D2017;D2018;D2019;D2020;D2021;D2022;D2023;D2024;D2025;D2026;D2026.5;D2027</Configurations>
    </PropertyGroup>

    <ItemGroup>
        <Compile Update="RevitCommand.Equal.cs">
            <DependentUpon>RevitCommand.cs</DependentUpon>
        </Compile>
        <Compile Update="RevitCommand.Greater.cs">
            <DependentUpon>RevitCommand.cs</DependentUpon>
        </Compile>
    </ItemGroup>

</Project>