<Project Sdk="Autodesk.Revit.Sdk.Refs/2.0.0">

    <PropertyGroup>
        <UseWpf>true</UseWpf>
        <RootNamespace>RevitPlugin.MultiProject</RootNamespace>

        <RevitVersion>2026</RevitVersion>
        <ShowBuildInfo>true</ShowBuildInfo>
        <IncludeEmbeddedLibrary>true</IncludeEmbeddedLibrary>
        
        <Configurations>Debug;Release</Configurations>
    </PropertyGroup>

    <ItemGroup>
        <Compile Update="RevitCommand.Equal.cs">
            <DependentUpon>RevitCommand.cs</DependentUpon>
        </Compile>
        <Compile Update="RevitCommand.Greater.cs">
            <DependentUpon>RevitCommand.cs</DependentUpon>
        </Compile>
    </ItemGroup>

</Project>