name: main

permissions:
  packages: write
  contents: write

on:
  workflow_dispatch:

env:
  output: bin
  project: Autodesk.Revit.Sdk.Refs
  configuration: Release

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      
      # Install the .NET Core workload
      - name: Install .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
      
      # Current date: https://stackoverflow.com/questions/60942067/get-current-date-and-time-in-github-workflows
      - name: Current date
        id: date
        run: echo "date=$(date +'%Y%m%d')" >> $GITHUB_ENV
      
      # Pack project: https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-pack
      - name: Pack
        run: dotnet pack -c ${{ env.configuration }} -o ${{ env.output }}
      
      # Upload the nuget package: https://github.com/marketplace/actions/upload-a-build-artifact
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          if-no-files-found: error
          name: ${{ env.project }}
          path: ${{ env.output }}/*.nupkg
      
#      # Publish the nuget package: https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-nuget-push
#      - name: Publish nuget
#        env:
#          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
#        run: dotnet nuget push ${{ env.output }}/**.nupkg -s https://api.nuget.org/v3/index.json -k $NUGET_API_KEY --skip-duplicate

      # Publish the nuget package: https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-nuget-push
      - name: Publish github
        env:
          NUGET_API_KEY: ${{ github.TOKEN }}
        run: dotnet nuget push ${{ env.output }}/**.nupkg -s https://nuget.pkg.github.com/${{ github.REPOSITORY_OWNER }}/index.json -k $NUGET_API_KEY --skip-duplicate
            
      # Publish release: https://github.com/softprops/action-gh-release
      - name: Publish Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ github.TOKEN }}
        with:
          tag_name: v${{ steps.date.outputs.date }}
          name: v${{ steps.date.outputs.date }}
          body_path: README.md
          draft: false
          prerelease: false
          files: |
            ${{ env.output }}/*.nupkg