name: main

permissions:
  packages: write
  contents: write

on:
  # on pull_request to master
  pull_request:
    types: [ opened, synchronize ]
    branches: [ main, master ]
  
  # manual
  workflow_dispatch:

env:
  output: bin
  project: Autodesk.Revit.Sdk.Refs
  configuration: Release
  default_branch: ${{ github.event.repository.default_branch }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      # Install the .NET 8.0 workload
      - name: Install .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      
      # Current date: https://stackoverflow.com/questions/60942067/get-current-date-and-time-in-github-workflows
      - name: Current date
        run: echo "date=$(date +'%Y.%m.%d')" >> $GITHUB_ENV
      
      # Pack project: https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-pack
      - name: Pack
        run: dotnet pack -c ${{ env.configuration }} -o ${{ env.output }}
      
      # Upload the nuget package: https://github.com/marketplace/actions/upload-a-build-artifact
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          if-no-files-found: error
          name: ${{ env.project }}
          path: ${{ env.output }}/*.nupkg
      
      # Publish the nuget package: https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-nuget-push
      - name: Publish nuget
        if: github.ref_name == env.default_branch
        run: dotnet nuget push ${{ env.output }}/**.nupkg -s https://api.nuget.org/v3/index.json -k ${{ secrets.NUGET_API_KEY }} --skip-duplicate

      # Publish the nuget package: https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-nuget-push
      - name: Publish github
        if: github.ref_name == env.default_branch
        run: dotnet nuget push ${{ env.output }}/**.nupkg -s https://nuget.pkg.github.com/${{ github.REPOSITORY_OWNER }}/index.json -k ${{ github.TOKEN }} --skip-duplicate
            
      # Publish release: https://github.com/softprops/action-gh-release
      - name: Publish Release
        if: github.ref_name == env.default_branch
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ github.TOKEN }}
        with:
          tag_name: v${{ env.date }}
          name: v${{ env.date }}
          body_path: README.md
          draft: false
          prerelease: false
          files: |
            ${{ env.output }}/*.nupkg